events{ 
	worker_connections 1024;
}

http{
	server{
		listen 81;
	
		location / {
			root "/mnt/c/Users/LENOVO CORE i7/Documents/Tareas 5to semestre/Desarrollo web/repoClonado/17289/nginx/3sitios/sitio1";
			index index.html;
		}
	}
}
